language: rust
cache: cargo

services:
  - postgresql

addons:
  homebrew:
    packages:
    - postgresql

before_script:
  - if [ "$TRAVIS_OS_NAME" == "osx" ] ; then brew services start postgresql ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ] ; then brew services list ; fi
  - if [ "$TRAVIS_OS_NAME" != "windows" ] ; then createuser dialogue_test ; fi
  - if [ "$TRAVIS_OS_NAME" != "windows" ] ; then createdb --owner=dialogue_test dialogue_test ; fi
  - if [ "$TRAVIS_OS_NAME" != "windows" ] ; then psql --command='drop schema if exists dialogue cascade;' --dbname=dialogue_test --username=dialogue_test ; fi

script:
  - cargo build --verbose
  - cargo build --verbose --release
  - if [ "$TRAVIS_OS_NAME" != "windows" ] ; then cargo run -- install --verbose --test-data --database-url=postgresql://dialogue_test@localhost/dialogue_test ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ] ; then sudo cargo test ; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ] ; then cargo test -- --skip server_tests ; fi

rust:
  - stable
  - beta
  - nightly

os:
  - osx
  - linux
  - windows

matrix:
  allow_failures:
    - rust: nightly
