language: rust
cache: cargo

script:
  - cargo build --verbose
  - cargo build --verbose --release

rust:
  - stable
  - beta
  - nightly

os:
  - osx
  - linux
  - windows

matrix:
  allow_failures:
    - rust: nightly
