language: rust
cache: cargo

services:
  - postgresql

before_script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ] ; then psql -c 'create user dialogue_test with login nosuperuser inherit nocreatedb nocreaterole noreplication;' -U postgres ; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ] ; then psql -c 'create database dialogue_test with owner dialogue_test;' -U postgres ; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ] ; then psql -c 'drop schema if exists dialogue cascade;' -d dialogue_test -U dialogue_test ; fi

script:
  - cargo build --verbose
  - cargo build --verbose --release
  - if [ "$TRAVIS_OS_NAME" == "linux" ] ; then cargo run -- install --verbose --test-data --database-url=postgresql://dialogue_test@localhost/dialogue_test ; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ] ; then cargo test ; fi

rust:
  - stable
  - beta
  - nightly

os:
  - osx
  - linux
  - windows

matrix:
  allow_failures:
    - rust: nightly
